// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD00TximR4aUCKFlVS0TkLl8kp0J88eTe4',
    appId: '1:293698711484:web:a4ddba3a6412e6672385b9',
    messagingSenderId: '293698711484',
    projectId: 'owlmart-6ef8b',
    authDomain: 'owlmart-6ef8b.firebaseapp.com',
    storageBucket: 'owlmart-6ef8b.firebasestorage.app',
    measurementId: 'G-CLSW2X7H5L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBar5tglX6iDb-uwE-4VZaceXDSRjAK79k',
    appId: '1:293698711484:android:2789b90d945a8fc72385b9',
    messagingSenderId: '293698711484',
    projectId: 'owlmart-6ef8b',
    storageBucket: 'owlmart-6ef8b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD612OhKS_tkys8LYWXGABsunIMEMj-eTg',
    appId: '1:293698711484:ios:262edec0d69684352385b9',
    messagingSenderId: '293698711484',
    projectId: 'owlmart-6ef8b',
    storageBucket: 'owlmart-6ef8b.firebasestorage.app',
    iosBundleId: 'com.example.owlmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD612OhKS_tkys8LYWXGABsunIMEMj-eTg',
    appId: '1:293698711484:ios:262edec0d69684352385b9',
    messagingSenderId: '293698711484',
    projectId: 'owlmart-6ef8b',
    storageBucket: 'owlmart-6ef8b.firebasestorage.app',
    iosBundleId: 'com.example.owlmart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD00TximR4aUCKFlVS0TkLl8kp0J88eTe4',
    appId: '1:293698711484:web:91cb7685e8277afa2385b9',
    messagingSenderId: '293698711484',
    projectId: 'owlmart-6ef8b',
    authDomain: 'owlmart-6ef8b.firebaseapp.com',
    storageBucket: 'owlmart-6ef8b.firebasestorage.app',
    measurementId: 'G-PT03JC0BC9',
  );
}
